# _config.yml
title: "NOCTURN X-ray Blog"
description: "Advancing Museum Imaging Technology & Security"
baseurl: ""
url: "https:///johntrue15.github.io" # Replace with your GitHub Pages URL

# Jekyll theme
# If you want to keep it simple, you can start with the default 'minima' theme
theme: minima

author:
  name: "Your Name"
  email: "your_email@example.com"

# Plugins (supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 10   # Show 10 posts per page
paginate_path: "/page:num/"

# Permalinks for your posts
permalink: /:year/:month/:day/:title/

# Exclude directories or files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
